import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BookOpenCheck, BrainCircuit, ChevronRight, CircleHelp, Crown, Flame, Gamepad2, Heart, Home, Languages, LockKeyhole, Rocket, RotateCcw, ShieldCheck, Sparkles, Star, Trophy, X, Zap } from 'lucide-react';
import curriculumDB from './data/curriculumDB.json';
import { ChestEngine, PuzzleEngine, RaceEngine, RpgEngine } from './engines';

const iconMap = { Layers: BookOpenCheck, Sparkles, Puzzle: BrainCircuit, ScrollText: BookOpenCheck, KeyRound: LockKeyhole, Languages, SpellCheck: Languages, TextCursorInput: BookOpenCheck, Swords: ShieldCheck, LockKeyhole, Gauge: Rocket, ArrowDownUp: BrainCircuit, Shield: ShieldCheck, Vault: LockKeyhole, Triangle: CircleHelp };
const subjectMap = { 中文: { icon: BookOpenCheck, color: 'coral', copy: '語感、古文與表達' }, 英文: { icon: Languages, color: 'blue', copy: '字詞、拼寫與語法' }, 數學: { icon: BrainCircuit, color: 'yellow', copy: '計算、推導與圖形' } };

function Logo() { return <div className="logo"><span className="logo-mark"><Sparkles /><Star /></span><span><b>EduQuest</b><small>邊學邊玩</small></span></div>; }
function XPBar({ xp, compact = false }) { const level = Math.floor(xp / 100) + 1; const progress = xp % 100; return <div className={`xp-cluster ${compact ? 'compact' : ''}`}><div className="xp-level">Lv.{level}</div><div><div className="xp-label"><span>知識 XP</span><b>{xp} / {Math.floor(xp / 100 + 1) * 100}</b></div><div className="xp-track"><span style={{ width: `${progress}%` }}></span></div></div></div>; }
function Hearts({ hearts, compact = false }) { return <div className={`hearts ${compact ? 'compact' : ''}`} aria-label={`尚餘 ${hearts} 顆心`}>{[0, 1, 2].map((heart) => <Heart key={heart} className={heart < hearts ? 'heart-full' : 'heart-empty'} fill={heart < hearts ? 'currentColor' : 'none'} />)}</div>; }
function HUD({ xp, hearts, onHome }) { return <header className="hud"><Logo /><div className="hud-stats"><XPBar xp={xp} /><div className="heart-wrap"><span>生命</span><Hearts hearts={hearts} /></div><button className="hud-home" onClick={onHome} aria-label="返回大廳"><Home size={19} /></button></div></header>; }

function Lobby({ xp, onBegin }) { return <main className="teacher-lobby page-enter"><header className="teacher-topbar"><Logo /><div className="teacher-top-actions"><span><ShieldCheck size={16} /> 教師課堂模式</span><XPBar xp={xp} compact /></div></header><section className="teacher-hero"><div><span className="eyebrow"><Sparkles size={16} /> EDUQUEST CLASSROOM</span><h1>開課三步，<em>全班即玩。</em></h1><p>按學生年級和科目選擇十題關卡，投影到大屏幕即可開始。每題均顯示即時回饋與解析，適合導入、操練及複習。</p><button className="teacher-start" onClick={onBegin}><Gamepad2 /> 開始選擇年級與科目 <ChevronRight /></button></div><aside className="lesson-guide"><span>課堂快速流程</span><ol><li><b>01</b><div><strong>選擇學段與年級</strong><small>小一至中六清楚分組</small></div></li><li><b>02</b><div><strong>選擇科目與範疇</strong><small>中、英、數，貼合課程重點</small></div></li><li><b>03</b><div><strong>開啟十題互動關卡</strong><small>即時答對／答錯回饋與解析</small></div></li></ol></aside></section><section className="teacher-feature-grid"><article><BookOpenCheck /><div><b>180 個課程 Topic</b><span>小一至中六・中英數</span></div></article><article><Star /><div><b>每關固定 10 題</b><span>適合一節課快速操練</span></div></article><article><Languages /><div><b>中學數學中英對照</b><span>題幹、答案及解析同步呈現</span></div></article></section><section className="teacher-notice"><Zap /><p><b>課堂提示：</b>教師可先在投影幕開啟關卡，再邀請學生輪流作答；答錯時請利用三秒解析帶領全班討論。</p><button onClick={onBegin}>立即開課 <ChevronRight size={16} /></button></section></main>; }

function LevelSelect({ xp, onBack, onPlay }) { const [grade, setGrade] = useState('P1'); const [subject, setSubject] = useState('中文'); const visibleTopics = useMemo(() => curriculumDB.topics.filter((topic) => topic.grade === grade && topic.subject === subject), [grade, subject]); const gradeGroups = [{ title:'小學', subtitle:'Primary', items:['P1','P2','P3','P4','P5','P6'] }, { title:'中學', subtitle:'Secondary', items:['S1','S2','S3','S4','S5','S6'] }]; return <main className="select-page teacher-select page-enter"><section className="select-header"><button className="back-btn" onClick={onBack}><ArrowLeft /> 返回教師首頁</button><XPBar xp={xp} compact /><div><span className="eyebrow"><Zap size={16} /> CLASS SETUP</span><h1>設定<span>本節課關卡</span></h1><p>先選年級，再選科目和課程範疇。每個關卡固定十題，適合投影與全班互動。</p></div></section><section className="selector-panel"><div className="selector-block grade-selector"><div className="selector-title"><span>01</span><div><b>選擇年級</b><small>小學及中學分欄顯示</small></div></div><div className="grade-columns">{gradeGroups.map((group) => <div className="grade-group" key={group.title}><div><b>{group.title}</b><small>{group.subtitle}</small></div><div className="grade-row">{group.items.map((item) => <button key={item} onClick={() => setGrade(item)} className={grade === item ? 'selected' : ''}>{item}</button>)}</div></div>)}</div></div><div className="selector-block"><div className="selector-title"><span>02</span><div><b>選擇科目</b><small>三大學習領域</small></div></div><div className="subject-row">{Object.entries(subjectMap).map(([name, info]) => { const Icon = info.icon; return <button key={name} onClick={() => setSubject(name)} className={`subject-choice ${info.color} ${subject === name ? 'selected' : ''}`}><Icon /><span><b>{name}</b><small>{info.copy}</small></span></button>; })}</div></div></section><section className="topic-section"><div className="topic-heading"><div><span className="eyebrow"><Star size={16} /> {grade}・{subject}</span><h2>選擇課程範疇，開始十題關卡。</h2></div><span>{visibleTopics.length} 個課程 Topic</span></div><div className="topic-grid">{visibleTopics.map((topic, index) => { const Icon = iconMap[topic.icon] || Star; const labels = { race: '選擇競速', puzzle: '文字拆解', rpg: 'RPG 對戰', chest: '寶箱密碼鎖' }; return <article className={`topic-card ${topic.engine}`} key={topic.id}><div className="topic-index">0{index + 1}</div><div className="topic-icon"><Icon /></div><span className="engine-chip">{labels[topic.engine]}</span>{topic.bilingual && <span className="bilingual-chip">中英對照</span>}<h3>{topic.title}{topic.titleEn && <small>{topic.titleEn}</small>}</h3><p>{topic.curriculumArea}</p><div className="topic-foot"><span>10 題・{topic.difficulty}</span><button onClick={() => onPlay(topic)}>開啟 <ChevronRight size={17} /></button></div></article>; })}</div></section></main>; }

function Feedback({ feedback }) { if (!feedback) return null; return <div className={`feedback-overlay ${feedback.correct ? 'success' : 'error'}`}><div className="feedback-icon">{feedback.correct ? <ShieldCheck /> : <X />}</div><div><b>{feedback.correct ? '答對！知識能量 +10' : '先別急，這題值得記住。'}</b><p>{feedback.correct ? '太好了，準備迎接下一個挑戰。' : <>正確答案：<strong>{feedback.answer}</strong><br />{feedback.explanation}{feedback.explanationEn && <><br /><span className="translation-line">English: {feedback.explanationEn}</span></>}</>}</p>{!feedback.correct && <span className="cooldown-text">正在整理提示… {feedback.countdown}s</span>}</div></div>; }

function GameScreen({ topic, xp, session, feedback, onAnswer, onHome }) { const question = topic.questions[session.index]; const labels = { race: '選擇競速', puzzle: '文字拆解／拼圖', rpg: 'RPG 怪物對戰', chest: '寶箱密碼鎖' }; const engineProps = { question, disabled: Boolean(feedback), onAnswer, questionKey: `${topic.id}-${session.index}` }; const Engine = topic.engine === 'race' ? RaceEngine : topic.engine === 'puzzle' ? PuzzleEngine : topic.engine === 'rpg' ? RpgEngine : ChestEngine; return <main className={`game-page ${feedback?.correct === false ? 'screen-shake' : ''}`}><HUD xp={xp} hearts={session.hearts} onHome={onHome} /><section className="game-progress"><div><button className="back-btn game-back" onClick={onHome}><ArrowLeft /> 結束本局</button><span>{topic.grade}・{topic.subject}・{labels[topic.engine]} {topic.bilingual && '・中英對照'}</span><h1>{topic.title}{topic.titleEn && <small>{topic.titleEn}</small>}</h1></div><div className="question-progress"><b>第 {session.index + 1} / {topic.questions.length} 題</b><div>{topic.questions.map((_, index) => <i key={index} className={index <= session.index ? 'active' : ''}></i>)}</div></div></section><section className="game-stage"><Engine {...engineProps} /></section><Feedback feedback={feedback} /></main>; }

function ResultScreen({ topic, session, xp, onReplay, onLobby }) { const isGameOver = session.gameOver; const correctCount = session.answers.filter((answer) => answer.correct).length; return <main className="result-page page-enter"><div className={`result-card ${isGameOver ? 'game-over' : 'victory'}`}><div className="result-burst" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div><div className="result-symbol">{isGameOver ? <Heart fill="currentColor" /> : <Trophy />}</div><span className="eyebrow">{isGameOver ? 'GAME OVER・下次再來' : 'MISSION COMPLETE・太強了！'}</span><h1>{isGameOver ? '這次先休息，整理後再衝。' : '任務完成，星圖已點亮！'}</h1><p>{isGameOver ? '每個錯誤都有解法。回到同一關再玩一次，把剛才的解析變成下一次的得分點。' : `你已完成 ${topic.grade} ${topic.subject} 的「${topic.title}」，知識能量已記錄在帳戶內。`}</p><div className="score-cards"><div><Zap /><span>本局獲得</span><b>+{session.sessionXp} XP</b></div><div><Heart fill="currentColor" /><span>尚餘生命</span><b>{session.hearts} / 3</b></div><div><Star fill="currentColor" /><span>答對題數</span><b>{correctCount} / {topic.questions.length}</b></div></div><div className="result-total"><XPBar xp={xp} /><span>累積知識 XP 已更新</span></div><div className="result-actions"><button className="secondary-cta" onClick={onLobby}><Home /> 返回大廳</button><button className="primary-cta" onClick={onReplay}><RotateCcw /> 再玩一次</button></div></div></main>; }

export default function App() { const demoParams = new URLSearchParams(window.location.search); const demoEngine = demoParams.get('demo'); const demoGrade = demoParams.get('grade'); const demoSubject = demoParams.get('subject'); const previewScreen = demoParams.get('view'); const demoTopic = demoEngine ? curriculumDB.topics.find((item) => item.engine === demoEngine && (!demoGrade || item.grade === demoGrade) && (!demoSubject || item.subject === demoSubject)) || null : null; const [screen, setScreen] = useState(demoTopic ? 'game' : previewScreen === 'select' ? 'select' : 'lobby'); const [xp, setXp] = useState(() => Number(localStorage.getItem('eduquest-xp') || 0)); const [topic, setTopic] = useState(demoTopic); const [session, setSession] = useState(demoTopic ? { index: 0, hearts: 3, sessionXp: 0, answers: [], gameOver: false } : null); const [feedback, setFeedback] = useState(null);
  useEffect(() => localStorage.setItem('eduquest-xp', String(xp)), [xp]);
  const startTopic = (selectedTopic) => { setTopic(selectedTopic); setSession({ index: 0, hearts: 3, sessionXp: 0, answers: [], gameOver: false }); setFeedback(null); setScreen('game'); };
  const endToLobby = () => { setFeedback(null); setScreen('lobby'); };
  const submitAnswer = (correct, selected) => { if (feedback || !session || !topic) return; const current = topic.questions[session.index]; const nextHearts = correct ? session.hearts : Math.max(0, session.hearts - 1); const nextSession = { ...session, hearts: nextHearts, sessionXp: session.sessionXp + (correct ? 10 : 0), answers: [...session.answers, { correct, selected }] }; if (correct) setXp((currentXp) => currentXp + 10); setSession(nextSession); setFeedback({ correct, answer: current.type === 'choice' ? current.options[current.answerIndex] : current.answer, explanation: current.explanation, explanationEn: current.explanationEn, countdown: correct ? 0 : 3 });
    if (correct) window.setTimeout(() => advance(nextSession), 1050); else { let remaining = 3; const timer = window.setInterval(() => { remaining -= 1; setFeedback((previous) => previous ? { ...previous, countdown: remaining } : previous); if (remaining <= 0) { window.clearInterval(timer); advance(nextSession); } }, 1000); }
  };
  const advance = (nextSession) => { setFeedback(null); if (nextSession.hearts <= 0) { setSession({ ...nextSession, gameOver: true }); setScreen('result'); return; } if (nextSession.index >= topic.questions.length - 1) { setSession(nextSession); setScreen('result'); return; } setSession({ ...nextSession, index: nextSession.index + 1 }); };
  if (screen === 'select') return <LevelSelect xp={xp} onBack={endToLobby} onPlay={startTopic} />;
  if (screen === 'game' && topic && session) return <GameScreen topic={topic} xp={xp} session={session} feedback={feedback} onAnswer={submitAnswer} onHome={endToLobby} />;
  if (screen === 'result' && topic && session) return <ResultScreen topic={topic} session={session} xp={xp} onReplay={() => startTopic(topic)} onLobby={endToLobby} />;
  return <Lobby xp={xp} onBegin={() => setScreen('select')} />;
}
