/* EduQuest 教師課堂版：以課程 Topic、題目板及閱讀篇章支援教師彈性開課。 */
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BookOpenCheck, BrainCircuit, ChevronRight, CircleHelp, Gamepad2, Heart, Home, Languages, LockKeyhole, RotateCcw, ShieldCheck, Sparkles, Star, Trophy, X, Zap } from 'lucide-react';
import curriculumDB from './data/curriculumDB.json';
import { ChestEngine, PuzzleEngine, RaceEngine, RpgEngine } from './engines';

const iconMap = { Layers: BookOpenCheck, Sparkles, Puzzle: BrainCircuit, ScrollText: BookOpenCheck, KeyRound: LockKeyhole, Languages, SpellCheck: Languages, TextCursorInput: BookOpenCheck, Swords: ShieldCheck, LockKeyhole, Gauge: Zap, ArrowDownUp: BrainCircuit, Shield: ShieldCheck, Vault: LockKeyhole, Triangle: CircleHelp };
const subjectMap = { 中文: { icon: BookOpenCheck, color: 'coral', copy: '閱讀、寫作與文化' }, 英文: { icon: Languages, color: 'blue', copy: '字詞、拼寫與語法' }, 數學: { icon: BrainCircuit, color: 'yellow', copy: '計算、推導與圖形' } };
const engineLabels = { race: '選擇競速', puzzle: '文字拆解', rpg: 'RPG 對戰', chest: '寶箱密碼鎖' };

function Logo() { return <div className="logo"><span className="logo-mark"><Sparkles /><Star /></span><span><b>EduQuest</b><small>邊學邊玩</small></span></div>; }
function XPBar({ xp, compact = false }) { const level = Math.floor(xp / 100) + 1; const progress = xp % 100; return <div className={`xp-cluster ${compact ? 'compact' : ''}`}><div className="xp-level">Lv.{level}</div><div><div className="xp-label"><span>知識 XP</span><b>{xp} / {Math.floor(xp / 100 + 1) * 100}</b></div><div className="xp-track"><span style={{ width: `${progress}%` }}></span></div></div></div>; }
function Hearts({ hearts }) { return <div className="hearts" aria-label={`尚餘 ${hearts} 顆心`}>{[0, 1, 2].map((heart) => <Heart key={heart} className={heart < hearts ? 'heart-full' : 'heart-empty'} fill={heart < hearts ? 'currentColor' : 'none'} />)}</div>; }
function HUD({ xp, hearts, onBack }) { return <header className="hud"><Logo /><div className="hud-stats"><XPBar xp={xp} /><div className="heart-wrap"><span>生命</span><Hearts hearts={hearts} /></div><button className="hud-home" onClick={onBack} aria-label="返回題目板"><Home size={19} /></button></div></header>; }

function Lobby({ xp, onBegin }) { return <main className="teacher-lobby page-enter"><header className="teacher-topbar"><Logo /><div className="teacher-top-actions"><span><ShieldCheck size={16} /> 教師課堂模式</span><XPBar xp={xp} compact /></div></header><section className="teacher-hero"><div><span className="eyebrow"><Sparkles size={16} /> EDUQUEST CLASSROOM</span><h1>開課三步，<em>全班即玩。</em></h1><p>按學生年級和科目選擇關卡，投影到大屏幕即可開始。小學中文提供十五題題目板和閱讀篇章，教師可按課堂時間逐題開啟。</p><button className="teacher-start" onClick={onBegin}><Gamepad2 /> 開始選擇年級與科目 <ChevronRight /></button></div><aside className="lesson-guide"><span>課堂快速流程</span><ol><li><b>01</b><div><strong>選擇學段與年級</strong><small>小一至中六清楚分組</small></div></li><li><b>02</b><div><strong>選擇科目與範疇</strong><small>中、英、數，貼合課程重點</small></div></li><li><b>03</b><div><strong>開啟題目或完整單元</strong><small>逐題彈性使用，附即時解析</small></div></li></ol></aside></section><section className="teacher-feature-grid"><article><BookOpenCheck /><div><b>180 個課程 Topic</b><span>小一至中六・中英數</span></div></article><article><Star /><div><b>小學中文每關 15 題</b><span>閱讀篇章可連答多題</span></div></article><article><Languages /><div><b>中學數學中英對照</b><span>題幹、答案及解析同步呈現</span></div></article></section><section className="teacher-notice"><Zap /><p><b>課堂提示：</b>開啟 Topic 後先選擇本節要做的題目；閱讀理解會先顯示篇章，答錯時可利用三秒解析帶領全班討論。</p><button onClick={onBegin}>立即開課 <ChevronRight size={16} /></button></section></main>; }

function LevelSelect({ xp, onBack, onOpenBoard }) { const [grade, setGrade] = useState('P1'); const [subject, setSubject] = useState('中文'); const visibleTopics = useMemo(() => curriculumDB.topics.filter((topic) => topic.grade === grade && topic.subject === subject), [grade, subject]); const gradeGroups = [{ title:'小學', subtitle:'Primary', items:['P1','P2','P3','P4','P5','P6'] }, { title:'中學', subtitle:'Secondary', items:['S1','S2','S3','S4','S5','S6'] }]; return <main className="select-page teacher-select page-enter"><section className="select-header"><button className="back-btn" onClick={onBack}><ArrowLeft /> 返回教師首頁</button><XPBar xp={xp} compact /><div><span className="eyebrow"><Zap size={16} /> CLASS SETUP</span><h1>設定<span>本節課關卡</span></h1><p>先選年級，再選科目和課程範疇。小學中文每個單元有十五題，其他單元維持十題；教師可逐題或完整開啟。</p></div></section><section className="selector-panel"><div className="selector-block grade-selector"><div className="selector-title"><span>01</span><div><b>選擇年級</b><small>小學及中學分欄顯示</small></div></div><div className="grade-columns">{gradeGroups.map((group) => <div className="grade-group" key={group.title}><div><b>{group.title}</b><small>{group.subtitle}</small></div><div className="grade-row">{group.items.map((item) => <button key={item} onClick={() => setGrade(item)} className={grade === item ? 'selected' : ''}>{item}</button>)}</div></div>)}</div></div><div className="selector-block"><div className="selector-title"><span>02</span><div><b>選擇科目</b><small>三大學習領域</small></div></div><div className="subject-row">{Object.entries(subjectMap).map(([name, info]) => { const Icon = info.icon; return <button key={name} onClick={() => setSubject(name)} className={`subject-choice ${info.color} ${subject === name ? 'selected' : ''}`}><Icon /><span><b>{name}</b><small>{info.copy}</small></span></button>; })}</div></div></section><section className="topic-section"><div className="topic-heading"><div><span className="eyebrow"><Star size={16} /> {grade}・{subject}</span><h2>選擇課程範疇，開啟題目板。</h2></div><span>{visibleTopics.length} 個課程 Topic</span></div><div className="topic-grid">{visibleTopics.map((topic, index) => { const Icon = iconMap[topic.icon] || Star; return <article className={`topic-card ${topic.engine}`} key={topic.id}><div className="topic-index">0{index + 1}</div><div className="topic-icon"><Icon /></div><span className="engine-chip">{engineLabels[topic.engine]}</span>{topic.bilingual && <span className="bilingual-chip">中英對照</span>}<h3>{topic.title}{topic.titleEn && <small>{topic.titleEn}</small>}</h3><p>{topic.curriculumArea}</p><div className="topic-foot"><span>{topic.questions.length} 題・{topic.difficulty}</span><button onClick={() => onOpenBoard(topic)}>題目板 <ChevronRight size={17} /></button></div></article>; })}</div></section></main>; }

function QuestionBoard({ topic, xp, onBack, onStart }) { const isPrimaryChinese = topic.subject === '中文' && /^P[1-6]$/.test(topic.grade); const readingCount = topic.questions.filter((question) => question.passageId).length; const labelFor = (question, index) => question.passageTitle ? `閱讀理解：${question.passageTitle}` : question.prompt.replace(`${topic.title}｜第${index + 1}題：`, ''); return <main className="question-board-page page-enter"><header className="board-header"><button className="back-btn" onClick={onBack}><ArrowLeft /> 返回課程範疇</button><Logo /><XPBar xp={xp} compact /></header><section className="board-intro"><span className="eyebrow"><Star size={16} /> MISSION CONSTELLATION・{topic.grade}・{topic.subject}</span><h1>{topic.title}</h1><p>{isPrimaryChinese ? '本單元有十五題。教師可按課堂進度逐題開啟；閱讀理解題會先呈現短篇材料，讓同學閱讀後再回答。' : '教師可選擇任一題開啟，或使用完整單元模式依次進行。'}</p><div className="board-stats"><span><BookOpenCheck /> {topic.questions.length} 題任務節點</span>{readingCount > 0 && <span><Sparkles /> {readingCount} 題閱讀理解</span>}<button className="full-unit-btn" onClick={() => onStart(0, 'full')}><Gamepad2 /> 連續闖關・全部充能</button></div></section><section className="question-grid" aria-label="題目選擇">{topic.questions.map((question, index) => <button className={`question-node ${question.passageId ? 'reading-node' : ''} ${index === 0 ? 'recommended-node' : ''} ${index > 10 ? 'future-node' : ''}`} key={`${topic.id}-${index}`} onClick={() => onStart(index, 'single')}><span className="question-node-number">{String(index + 1).padStart(2, '0')}</span>{index === 0 && <span className="recommended-badge">下一步已充能</span>}<span className="question-node-kind">{question.passageId ? '閱讀理解' : engineLabels[topic.engine]}</span><strong>{labelFor(question, index)}</strong><small>{question.passageId ? '先讀篇章，再作答・+10 XP' : '開啟本題・+10 XP'} <ChevronRight size={14} /></small></button>)}</section></main>; }

function Feedback({ feedback }) { if (!feedback) return null; return <div className={`feedback-overlay ${feedback.correct ? 'success' : 'error'}`}><div className="feedback-icon">{feedback.correct ? <ShieldCheck /> : <X />}</div><div><b>{feedback.correct ? '答對！知識能量 +10' : '先別急，這題值得記住。'}</b><p>{feedback.correct ? '太好了，準備迎接下一個挑戰。' : <>正確答案：<strong>{feedback.answer}</strong><br />{feedback.explanation}{feedback.explanationEn && <><br /><span className="translation-line">English: {feedback.explanationEn}</span></>}</>}</p>{!feedback.correct && <span className="cooldown-text">正在整理提示… {feedback.countdown}s</span>}</div></div>; }

function GameScreen({ topic, xp, session, feedback, onAnswer, onExit }) { const question = topic.questions[session.index]; const Engine = topic.engine === 'race' ? RaceEngine : topic.engine === 'puzzle' ? PuzzleEngine : topic.engine === 'rpg' ? RpgEngine : ChestEngine; const engineProps = { question, disabled: Boolean(feedback), onAnswer, questionKey: `${topic.id}-${session.index}` }; return <main className={`game-page ${feedback?.correct === false ? 'screen-shake' : ''}`}><HUD xp={xp} hearts={session.hearts} onBack={onExit} /><section className="game-progress"><div><button className="back-btn game-back" onClick={onExit}><ArrowLeft /> 返回題目板</button><span>{topic.grade}・{topic.subject}・{engineLabels[topic.engine]} {topic.bilingual && '・中英對照'}</span><h1>{topic.title}{topic.titleEn && <small>{topic.titleEn}</small>}</h1></div><div className="question-progress"><b>第 {session.index + 1} / {topic.questions.length} 題</b><div>{topic.questions.map((_, index) => <i key={index} className={index === session.index ? 'active' : ''}></i>)}</div></div></section>{question.passageText && <article className="reading-passage"><div><BookOpenCheck /><span>閱讀篇章・{question.passageTitle}</span></div><p>{question.passageText}</p><small>請先閱讀篇章，再回答本題。</small></article>}<section className="game-stage"><Engine {...engineProps} /></section><Feedback feedback={feedback} /></main>; }

function ResultScreen({ topic, session, xp, onReplay, onLobby, onQuestions }) { const isGameOver = session.gameOver; const correctCount = session.answers.filter((answer) => answer.correct).length; const isSingle = session.mode === 'single'; return <main className="result-page page-enter"><div className={`result-card ${isGameOver ? 'game-over' : 'victory'}`}><div className="result-burst" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div><div className="result-symbol">{isGameOver ? <Heart fill="currentColor" /> : <Trophy />}</div><span className="eyebrow">{isGameOver ? 'GAME OVER・下次再來' : isSingle ? 'QUESTION COMPLETE・本題完成' : 'MISSION COMPLETE・太強了！'}</span><h1>{isGameOver ? '這次先休息，整理後再衝。' : isSingle ? '本題完成，選擇下一題吧！' : '任務完成，星圖已點亮！'}</h1><p>{isGameOver ? '每個錯誤都有解法。回到題目板，選擇合適題目再試一次。' : `你已完成 ${topic.grade} ${topic.subject} 的「${topic.title}」${isSingle ? '其中一題' : '完整單元'}。`}</p><div className="score-cards"><div><Zap /><span>本次獲得</span><b>+{session.sessionXp} XP</b></div><div><Heart fill="currentColor" /><span>尚餘生命</span><b>{session.hearts} / 3</b></div><div><Star fill="currentColor" /><span>答對題數</span><b>{correctCount} / {isSingle ? 1 : topic.questions.length}</b></div></div><div className="result-total"><XPBar xp={xp} /><span>累積知識 XP 已更新</span></div><div className="result-actions"><button className="secondary-cta" onClick={onLobby}><Home /> 返回大廳</button><button className="secondary-cta" onClick={onQuestions}><BookOpenCheck /> 題目板</button><button className="primary-cta" onClick={onReplay}><RotateCcw /> 再試一次</button></div></div></main>; }

export default function App() { const params = new URLSearchParams(window.location.search); const demoEngine = params.get('demo'); const demoGrade = params.get('grade'); const demoSubject = params.get('subject'); const previewScreen = params.get('view'); const demoTopic = demoEngine ? curriculumDB.topics.find((item) => item.engine === demoEngine && (!demoGrade || item.grade === demoGrade) && (!demoSubject || item.subject === demoSubject)) || null : null; const previewTopic = previewScreen === 'questions' ? curriculumDB.topics.find((item) => item.grade === (demoGrade || 'P3') && item.subject === (demoSubject || '中文') && (!params.get('topic') || item.title.includes(params.get('topic')))) || null : null; const initialTopic = demoTopic || previewTopic; const [screen, setScreen] = useState(demoTopic ? 'game' : previewTopic ? 'questions' : previewScreen === 'select' ? 'select' : 'lobby'); const [xp, setXp] = useState(() => Number(localStorage.getItem('eduquest-xp') || 0)); const [topic, setTopic] = useState(initialTopic); const [session, setSession] = useState(demoTopic ? { index:0, hearts:3, sessionXp:0, answers:[], gameOver:false, mode:'full' } : null); const [feedback, setFeedback] = useState(null);
  useEffect(() => localStorage.setItem('eduquest-xp', String(xp)), [xp]);
  const openQuestionBoard = (selectedTopic) => { setTopic(selectedTopic); setSession(null); setFeedback(null); setScreen('questions'); };
  const startTopic = (index = 0, mode = 'full') => { if (!topic) return; setSession({ index, hearts:3, sessionXp:0, answers:[], gameOver:false, mode }); setFeedback(null); setScreen('game'); };
  const endToLobby = () => { setFeedback(null); setSession(null); setScreen('lobby'); };
  const backToQuestions = () => { setFeedback(null); setSession(null); setScreen('questions'); };
  const submitAnswer = (correct, selected) => { if (feedback || !session || !topic) return; const current = topic.questions[session.index]; const nextHearts = correct ? session.hearts : Math.max(0, session.hearts - 1); const nextSession = { ...session, hearts: nextHearts, sessionXp: session.sessionXp + (correct ? 10 : 0), answers:[...session.answers, { correct, selected }] }; if (correct) setXp((value) => value + 10); setSession(nextSession); setFeedback({ correct, answer:current.type === 'choice' ? current.options[current.answerIndex] : current.answer, explanation:current.explanation, explanationEn:current.explanationEn, countdown:correct ? 0 : 3 }); if (correct) window.setTimeout(() => advance(nextSession), 1050); else { let remaining=3; const timer=window.setInterval(() => { remaining -= 1; setFeedback((previous) => previous ? { ...previous, countdown:remaining } : previous); if (remaining <= 0) { window.clearInterval(timer); advance(nextSession); } }, 1000); } };
  const advance = (nextSession) => { setFeedback(null); if (nextSession.mode === 'single') { setSession({ ...nextSession, gameOver:nextSession.hearts <= 0 }); setScreen('result'); return; } if (nextSession.hearts <= 0) { setSession({ ...nextSession, gameOver:true }); setScreen('result'); return; } if (nextSession.index >= topic.questions.length - 1) { setSession(nextSession); setScreen('result'); return; } setSession({ ...nextSession, index:nextSession.index + 1 }); };
  if (screen === 'select') return <LevelSelect xp={xp} onBack={endToLobby} onOpenBoard={openQuestionBoard} />;
  if (screen === 'questions' && topic) return <QuestionBoard topic={topic} xp={xp} onBack={() => setScreen('select')} onStart={startTopic} />;
  if (screen === 'game' && topic && session) return <GameScreen topic={topic} xp={xp} session={session} feedback={feedback} onAnswer={submitAnswer} onExit={backToQuestions} />;
  if (screen === 'result' && topic && session) return <ResultScreen topic={topic} session={session} xp={xp} onReplay={() => startTopic(session.index, session.mode)} onLobby={endToLobby} onQuestions={backToQuestions} />;
  return <Lobby xp={xp} onBegin={() => setScreen('select')} />;
}
