/* EduQuest 教師課堂版：以課程 Topic、題目板及閱讀篇章支援教師彈性開課。 */
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BookOpenCheck, BrainCircuit, ChevronRight, CircleHelp, Gamepad2, Heart, Home, Languages, LockKeyhole, PenLine, RotateCcw, ShieldCheck, Sparkles, Star, Trophy, X, Zap } from 'lucide-react';
import curriculumDB from './data/curriculumDB.json';
import { ChestEngine, CompositionEngine, PuzzleEngine, RaceEngine, RpgEngine } from './engines';

const iconMap = { Layers: BookOpenCheck, Sparkles, Puzzle: BrainCircuit, ScrollText: BookOpenCheck, KeyRound: LockKeyhole, Languages, SpellCheck: Languages, TextCursorInput: BookOpenCheck, Swords: ShieldCheck, LockKeyhole, Gauge: Zap, ArrowDownUp: BrainCircuit, Shield: ShieldCheck, Vault: LockKeyhole, Triangle: CircleHelp, PenLine };
const subjectMap = { 中文: { icon: BookOpenCheck, color: 'coral', copy: '識字、句式、修辭、詩歌與文言' } };
const engineLabels = { race: '選擇競速', puzzle: '文字拆解', rpg: 'RPG 對戰', chest: '寶箱密碼鎖', composition: '寫作工房' };

function Logo() { return <div className="logo"><span className="logo-mark"><i></i><i></i><Sparkles /><Star /></span><span className="logo-copy"><b>Edu<span>Quest</span></b><small>邊學邊玩・知識星圖</small></span></div>; }
function XPBar({ xp, compact = false }) { const level = Math.floor(xp / 100) + 1; const progress = xp % 100; return <div className={`xp-cluster ${compact ? 'compact' : ''}`}><div className="xp-level">Lv.{level}</div><div><div className="xp-label"><span>知識 XP</span><b>{xp} / {Math.floor(xp / 100 + 1) * 100}</b></div><div className="xp-track"><span style={{ width: `${progress}%` }}></span></div></div></div>; }
function Hearts({ hearts }) { return <div className="hearts" aria-label={`尚餘 ${hearts} 顆心`}>{[0, 1, 2].map((heart) => <Heart key={heart} className={heart < hearts ? 'heart-full' : 'heart-empty'} fill={heart < hearts ? 'currentColor' : 'none'} />)}</div>; }
function HUD({ xp, hearts, onBack }) { return <header className="hud"><Logo /><div className="hud-stats"><XPBar xp={xp} /><div className="heart-wrap"><span>生命</span><Hearts hearts={hearts} /></div><button className="hud-home" onClick={onBack} aria-label="返回題目板"><Home size={19} /></button></div></header>; }

function Lobby({ xp, onBegin }) { return <main className="teacher-lobby page-enter"><header className="teacher-topbar"><Logo /><div className="teacher-top-actions"><span><ShieldCheck size={16} /> 教師課堂模式</span><XPBar xp={xp} compact /></div></header><section className="teacher-hero"><div><span className="eyebrow"><Sparkles size={16} /> EDUQUEST CLASSROOM</span><h1>小學中文，<em>逐級精準練。</em></h1><p>目前只載入你提供的小一至小六中文課程：識字、量詞、句式、成語、修辭、古詩格式及文言基礎。每關十五題，教師可按課堂時間逐題開啟。</p><button className="teacher-start" onClick={onBegin}><Gamepad2 /> 開始選擇小學中文年級 <ChevronRight /></button></div><aside className="lesson-guide"><span>課堂快速流程</span><ol><li><b>01</b><div><strong>選擇小一至小六</strong><small>目前只開放小學中文</small></div></li><li><b>02</b><div><strong>選擇指定範疇</strong><small>完全依照分級課程重點</small></div></li><li><b>03</b><div><strong>開啟單題或完整單元</strong><small>每關十五題，附即時解析</small></div></li></ol></aside></section><section className="teacher-feature-grid"><article><BookOpenCheck /><div><b>23 個指定中文單元</b><span>小一至小六・按範疇重建</span></div></article><article><Star /><div><b>每關固定 15 題</b><span>題幹明確、答案可推導</span></div></article><article><LockKeyhole /><div><b>其他科目暫未開放</b><span>等待課程範疇後再加入</span></div></article></section><section className="teacher-notice"><Zap /><p><b>課堂提示：</b>開啟單元後，先選擇本節要做的題目；每次答題後按「下一題」繼續。英文、數學和中學中文內容已清空，待你日後上載課程後才重新編排。</p><button onClick={onBegin}>立即開課 <ChevronRight size={16} /></button></section></main>; }

function LevelSelect({ xp, onBack, onOpenBoard }) { const [grade, setGrade] = useState('P1'); const [subject] = useState('中文'); const visibleTopics = useMemo(() => curriculumDB.topics.filter((topic) => topic.grade === grade && topic.subject === subject), [grade, subject]); const gradeGroups = [{ title:'小學中文', subtitle:'Primary Chinese', items:['P1','P2','P3','P4','P5','P6'] }]; return <main className="select-page teacher-select page-enter"><section className="select-header"><button className="back-btn" onClick={onBack}><ArrowLeft /> 返回教師首頁</button><XPBar xp={xp} compact /><div><span className="eyebrow"><Zap size={16} /> CLASS SETUP</span><h1>設定<span>小學中文關卡</span></h1><p>目前只提供你指定的小一至小六中文範疇。每個單元有十五題，教師可逐題或完整開啟；其他科目將於上載課程後再加入。</p></div></section><section className="selector-panel"><div className="selector-block grade-selector"><div className="selector-title"><span>01</span><div><b>選擇年級</b><small>小一至小六</small></div></div><div className="grade-columns">{gradeGroups.map((group) => <div className="grade-group" key={group.title}><div><b>{group.title}</b><small>{group.subtitle}</small></div><div className="grade-row">{group.items.map((item) => <button key={item} onClick={() => setGrade(item)} className={grade === item ? 'selected' : ''}>{item}</button>)}</div></div>)}</div></div><div className="selector-block"><div className="selector-title"><span>02</span><div><b>目前課程</b><small>其他科目待你上載範疇</small></div></div><div className="subject-row">{Object.entries(subjectMap).map(([name, info]) => { const Icon = info.icon; return <div key={name} className={`subject-choice ${info.color} selected`}><Icon /><span><b>{name}</b><small>{info.copy}</small></span></div>; })}</div></div></section><section className="topic-section"><div className="topic-heading"><div><span className="eyebrow"><Star size={16} /> {grade}・{subject}</span><h2>選擇指定課程範疇，開啟題目板。</h2></div><span>{visibleTopics.length} 個課程 Topic</span></div><div className="topic-grid">{visibleTopics.map((topic, index) => { const Icon = iconMap[topic.icon] || Star; return <article className={`topic-card ${topic.engine}`} key={topic.id}><div className="topic-index">0{index + 1}</div><div className="topic-icon"><Icon /></div><span className="engine-chip">{engineLabels[topic.engine]}</span><h3>{topic.title}</h3><p>{topic.curriculumArea}</p><div className="topic-foot"><span>{topic.questions.length} 題・{topic.difficulty}</span><button onClick={() => onOpenBoard(topic)}>題目板 <ChevronRight size={17} /></button></div></article>; })}</div></section></main>; }

function QuestionBoard({ topic, xp, onBack, onStart }) { const labelFor = (question, index) => question.prompt.replace(`${topic.title}｜第${index + 1}題：`, ''); return <main className="question-board-page page-enter"><header className="board-header"><button className="back-btn" onClick={onBack}><ArrowLeft /> 返回課程範疇</button><Logo /><XPBar xp={xp} compact /></header><section className="board-intro"><span className="eyebrow"><Star size={16} /> MISSION CONSTELLATION・{topic.grade}・中文</span><h1>{topic.title}</h1><p>本單元有十五題，內容完全對應該級指定範疇。教師可按課堂進度逐題開啟，或連續完成整個單元。</p><div className="board-stats"><span><BookOpenCheck /> {topic.questions.length} 題任務節點</span><button className="full-unit-btn" onClick={() => onStart(0, 'full')}><Gamepad2 /> 連續闖關・全部充能</button></div></section><section className="question-grid" aria-label="題目選擇">{topic.questions.map((question, index) => <button className={`question-node ${index === 0 ? 'recommended-node' : ''} ${index > 10 ? 'future-node' : ''}`} key={`${topic.id}-${index}`} onClick={() => onStart(index, 'single')}><span className="question-node-number">{String(index + 1).padStart(2, '0')}</span>{index === 0 && <span className="recommended-badge">下一步已充能</span>}<span className="question-node-kind">{engineLabels[topic.engine]}</span><strong>{labelFor(question, index)}</strong><small>開啟本題・+10 XP <ChevronRight size={14} /></small></button>)}</section></main>; }

function Feedback({ feedback, onNext }) { if (!feedback) return null; const nextLabel = feedback.isFinal ? '完成本題' : '下一題'; return <div className={`feedback-overlay ${feedback.correct ? 'success' : 'error'}`}><div className="feedback-icon">{feedback.correct ? <ShieldCheck /> : <X />}</div><div><b>{feedback.correct ? '答對！知識能量 +10' : '先別急，這題值得記住。'}</b><p>{feedback.correct ? '太好了，已準備好下一題。' : <>正確答案：<strong>{feedback.answer}</strong><br />{feedback.explanation}{feedback.explanationEn && <><br /><span className="translation-line">English: {feedback.explanationEn}</span></>}</>}</p>{!feedback.correct && !feedback.ready && <span className="cooldown-text">請帶領全班閱讀解析… {feedback.countdown}s</span>}<button className="feedback-next-btn" disabled={!feedback.ready} onClick={onNext}><ChevronRight size={18} /> {feedback.ready ? nextLabel : '請先閱讀解析'}</button></div></div>; }

function GameScreen({ topic, xp, session, feedback, onAnswer, onNext, onExit }) { const question = topic.questions[session.index]; const feedbackPreview = new URLSearchParams(window.location.search).get('feedback'); const displayedFeedback = feedback || (feedbackPreview ? { correct:feedbackPreview !== 'wrong', answer:'小說', explanation:'這是版面驗證預覽；正式答題時會顯示該題的正解與解析。', countdown:0, ready:true, isFinal:false } : null); const Engine = topic.engine === 'race' ? RaceEngine : topic.engine === 'puzzle' ? PuzzleEngine : topic.engine === 'rpg' ? RpgEngine : topic.engine === 'composition' ? CompositionEngine : ChestEngine; const engineProps = { question, disabled: Boolean(displayedFeedback), onAnswer, questionKey: `${topic.id}-${session.index}` }; return <main className={`game-page ${displayedFeedback?.correct === false ? 'screen-shake' : ''}`}><HUD xp={xp} hearts={session.hearts} onBack={onExit} /><section className="game-progress"><div><button className="back-btn game-back" onClick={onExit}><ArrowLeft /> 返回題目板</button><span>{topic.grade}・{topic.subject}・{engineLabels[topic.engine]} {topic.bilingual && '・中英對照'}</span><h1>{topic.title}{topic.titleEn && <small>{topic.titleEn}</small>}</h1></div><div className="question-progress"><b>第 {session.index + 1} / {topic.questions.length} 題</b><div>{topic.questions.map((_, index) => <i key={index} className={index === session.index ? 'active' : ''}></i>)}</div></div></section>{question.passageText && <article className="reading-passage"><div><BookOpenCheck /><span>閱讀篇章・{question.passageTitle}</span></div><p>{question.passageText}</p><small>請先閱讀篇章，再回答本題。</small></article>}<section className="game-stage"><Engine {...engineProps} /></section><Feedback feedback={displayedFeedback} onNext={onNext} /></main>; }

function ResultScreen({ topic, session, xp, onReplay, onLobby, onQuestions }) { const isGameOver = session.gameOver; const correctCount = session.answers.filter((answer) => answer.correct).length; const isSingle = session.mode === 'single'; return <main className="result-page page-enter"><div className={`result-card ${isGameOver ? 'game-over' : 'victory'}`}><div className="result-burst" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div><div className="result-symbol">{isGameOver ? <Heart fill="currentColor" /> : <Trophy />}</div><span className="eyebrow">{isGameOver ? 'GAME OVER・下次再來' : isSingle ? 'QUESTION COMPLETE・本題完成' : 'MISSION COMPLETE・太強了！'}</span><h1>{isGameOver ? '這次先休息，整理後再衝。' : isSingle ? '本題完成，選擇下一題吧！' : '任務完成，星圖已點亮！'}</h1><p>{isGameOver ? '每個錯誤都有解法。回到題目板，選擇合適題目再試一次。' : `你已完成 ${topic.grade} ${topic.subject} 的「${topic.title}」${isSingle ? '其中一題' : '完整單元'}。`}</p><div className="score-cards"><div><Zap /><span>本次獲得</span><b>+{session.sessionXp} XP</b></div><div><Heart fill="currentColor" /><span>尚餘生命</span><b>{session.hearts} / 3</b></div><div><Star fill="currentColor" /><span>答對題數</span><b>{correctCount} / {isSingle ? 1 : topic.questions.length}</b></div></div><div className="result-total"><XPBar xp={xp} /><span>累積知識 XP 已更新</span></div><div className="result-actions"><button className="secondary-cta" onClick={onLobby}><Home /> 返回大廳</button><button className="secondary-cta" onClick={onQuestions}><BookOpenCheck /> 題目板</button><button className="primary-cta" onClick={onReplay}><RotateCcw /> 再試一次</button></div></div></main>; }

export default function App() { const params = new URLSearchParams(window.location.search); const demoEngine = params.get('demo'); const demoGrade = params.get('grade'); const demoSubject = params.get('subject'); const previewScreen = params.get('view'); const feedbackPreview = params.get('feedback'); const demoTopic = demoEngine ? curriculumDB.topics.find((item) => item.engine === demoEngine && (!demoGrade || item.grade === demoGrade) && (!demoSubject || item.subject === demoSubject)) || null : null; const previewTopic = previewScreen === 'questions' ? curriculumDB.topics.find((item) => item.grade === (demoGrade || 'P3') && item.subject === (demoSubject || '中文') && (!params.get('topic') || item.title.includes(params.get('topic')))) || null : null; const initialTopic = demoTopic || previewTopic; const [screen, setScreen] = useState(demoTopic ? 'game' : previewTopic ? 'questions' : previewScreen === 'select' ? 'select' : 'lobby'); const [xp, setXp] = useState(() => Number(localStorage.getItem('eduquest-xp') || 0)); const [topic, setTopic] = useState(initialTopic); const [session, setSession] = useState(demoTopic ? { index:0, hearts:3, sessionXp:0, answers:[], gameOver:false, mode:'full' } : null); const [feedback, setFeedback] = useState(() => feedbackPreview && demoTopic ? { correct:feedbackPreview !== 'wrong', answer:'小說', explanation:'這是版面驗證預覽；正式答題時會顯示該題的正解與解析。', countdown:0, ready:true, isFinal:false } : null);
  useEffect(() => localStorage.setItem('eduquest-xp', String(xp)), [xp]);
  useEffect(() => { if (feedbackPreview && demoTopic) setFeedback({ correct:feedbackPreview !== 'wrong', answer:'小說', explanation:'這是版面驗證預覽；正式答題時會顯示該題的正解與解析。', countdown:0, ready:true, isFinal:false }); }, [feedbackPreview, demoTopic?.id]);
  const openQuestionBoard = (selectedTopic) => { setTopic(selectedTopic); setSession(null); setFeedback(null); setScreen('questions'); };
  const startTopic = (index = 0, mode = 'full') => { if (!topic) return; setSession({ index, hearts:3, sessionXp:0, answers:[], gameOver:false, mode }); setFeedback(null); setScreen('game'); };
  const endToLobby = () => { setFeedback(null); setSession(null); setScreen('lobby'); };
  const backToQuestions = () => { setFeedback(null); setSession(null); setScreen('questions'); };
  const submitAnswer = (correct, selected) => { if (feedback || !session || !topic) return; const current = topic.questions[session.index]; const nextHearts = correct ? session.hearts : Math.max(0, session.hearts - 1); const nextSession = { ...session, hearts: nextHearts, sessionXp: session.sessionXp + (correct ? 10 : 0), answers:[...session.answers, { correct, selected }] }; if (correct) setXp((value) => value + 10); setSession(nextSession); setFeedback({ correct, answer:current.type === 'choice' ? current.options[current.answerIndex] : current.answer, explanation:current.explanation, explanationEn:current.explanationEn, countdown:correct ? 0 : 3, ready:correct, isFinal:nextSession.mode === 'single' || nextSession.hearts <= 0 || nextSession.index >= topic.questions.length - 1 }); if (!correct) { let remaining=3; const timer=window.setInterval(() => { remaining -= 1; setFeedback((previous) => previous ? { ...previous, countdown:remaining, ready:remaining <= 0 } : previous); if (remaining <= 0) window.clearInterval(timer); }, 1000); } };
  const advance = (nextSession) => { setFeedback(null); if (nextSession.mode === 'single') { setSession({ ...nextSession, gameOver:nextSession.hearts <= 0 }); setScreen('result'); return; } if (nextSession.hearts <= 0) { setSession({ ...nextSession, gameOver:true }); setScreen('result'); return; } if (nextSession.index >= topic.questions.length - 1) { setSession(nextSession); setScreen('result'); return; } setSession({ ...nextSession, index:nextSession.index + 1 }); };
  if (screen === 'select') return <LevelSelect xp={xp} onBack={endToLobby} onOpenBoard={openQuestionBoard} />;
  if (screen === 'questions' && topic) return <QuestionBoard topic={topic} xp={xp} onBack={() => setScreen('select')} onStart={startTopic} />;
  if (screen === 'game' && topic && session) return <GameScreen topic={topic} xp={xp} session={session} feedback={feedback} onAnswer={submitAnswer} onNext={() => advance(session)} onExit={backToQuestions} />;
  if (screen === 'result' && topic && session) return <ResultScreen topic={topic} session={session} xp={xp} onReplay={() => startTopic(session.index, session.mode)} onLobby={endToLobby} onQuestions={backToQuestions} />;
  return <Lobby xp={xp} onBegin={() => setScreen('select')} />;
}
