/* 彩色課程工作檯：金錢及分數以草綠紙軌、拖曳與點選替代操作支援投影課堂。 */
import { ArrowLeft, Check, ChevronRight, RotateCcw, ShoppingBasket as ShoppingBasketIcon, Sparkles, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { pauseExamTimer } from '../lib/examTimerStore';
import ExamTimer from './ExamTimer';
import HintSatchel from './HintSatchel';
import UnitResultSummary from './UnitResultSummary';
import '../mathLearning.css';

const shuffle = (items) => { const next = [...items]; for (let i = next.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [next[i], next[j]] = [next[j], next[i]]; } return next; };
const gradeLabel = (grade) => ({ P1: '小一', P3: '小三' }[grade] || grade);
const coin = (value, key) => <span key={key} className={`hk-coin coin-${value}`}>${value}</span>;

function Frame({ unit, task }) { const grade = unit.id.split('-')[0]; return <><header className="activity-workbench-frame math-activity-frame"><span className="activity-file-tab">{grade}<br />MATH</span><div className="activity-brand-lockup"><span className="activity-brand-mark"><i></i><i></i><i></i><Sparkles size={18} /></span><div><b>Edu<span>Quest</span></b><small>小學課堂展示版</small></div></div><div className="activity-course-file"><span>{gradeLabel(grade)}・數學</span><b>{unit.area}・{unit.title}</b></div>{task !== '結算' && <ExamTimer />}<div className="activity-task-stamp"><span>教師工作紙</span><b>{task}</b></div></header>{task !== '結算' && <HintSatchel title="操作錦囊" hint="可先拖曳操作；在平板或投影觸控時，也可改用點選操作。" />}</>; }

function Pie({ total, filled, label, draggable, onDragStart, onClick, selected }) { const degree = (filled / total) * 360; return <button type="button" draggable={draggable} onDragStart={onDragStart} onClick={onClick} className={`fraction-pie ${selected ? 'selected' : ''}`} style={{ background: `conic-gradient(#55bd86 0deg ${degree}deg,#f8fffb ${degree}deg 360deg)` }} aria-label={`${label || `${filled}/${total}`} 分數圓餅`}><i>{label || `${filled}/${total}`}</i></button>; }

function ShoppingBasket({ question, disabled, onAnswer }) { const [inBasket, setInBasket] = useState(false); const paid = question.paidCoins.reduce((total, value) => total + value, 0); const change = paid - question.price; const add = () => { if (!disabled) setInBasket(true); }; return <section className="shopping-workbench"><div className="shop-item"><span className="shop-icon">{question.icon}</span><div><small>文具店商品</small><b>{question.item}</b><strong>${question.price}</strong></div><button disabled={disabled || inBasket} onClick={add}>{inBasket ? '已加入購物籃' : '加入購物籃'} <ShoppingBasketIcon size={16} /></button></div><div className="basket-panel"><div><ShoppingBasketIcon size={23} /><span>我的購物籃</span></div>{inBasket ? <section><b>{question.icon} {question.item}</b><small>售價 ${question.price}</small></section> : <p>先把商品加入購物籃。</p>}</div><div className="payment-panel"><span>我付款</span><div>{question.paidCoins.map((value, index) => coin(value, index))}</div><b>共付 ${paid}</b></div><div className="change-drop" onClick={() => inBasket && onAnswer(change)} role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter' && inBasket) onAnswer(change); }}><span>找續區</span><b>{inBasket ? '按這裡確認找續' : '先加入商品'}</b></div></section>; }

function FractionBuild({ question, disabled, onAnswer }) { const [filled, setFilled] = useState(new Set()); const [dragging, setDragging] = useState(false); const addPiece = (index) => { if (disabled || filled.has(index) || filled.size >= question.target) return; setFilled((current) => new Set([...current, index])); }; const removePiece = (index) => { if (!disabled && filled.has(index)) setFilled((current) => { const next = new Set(current); next.delete(index); return next; }); }; const pieces = Array.from({ length: question.total }, (_, index) => index); return <section className="fraction-builder"><div className="pie-palette"><span>切餅盤</span>{pieces.map((index) => <button key={index} type="button" draggable={!disabled && !filled.has(index)} onDragStart={() => setDragging(true)} onDragEnd={() => setDragging(false)} onClick={() => addPiece(index)} className={filled.has(index) ? 'used' : ''}>切餅 {index + 1}</button>)}</div><div className={`pie-drop-zone ${dragging ? 'drag-over' : ''}`} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); setDragging(false); const open = pieces.find((index) => !filled.has(index)); if (open !== undefined) addPiece(open); }}><Pie total={question.total} filled={filled.size} label={`${filled.size}/${question.total}`} /><small>已放入 {filled.size} 塊</small><div>{pieces.map((index) => <button type="button" key={index} aria-label={`第 ${index + 1} 塊${filled.has(index) ? '已放入，按下可取回' : '未放入，按下可加入'}`} className={filled.has(index) ? 'filled' : ''} onClick={() => filled.has(index) ? removePiece(index) : addPiece(index)}></button>)}</div></div>{filled.size === question.target && <button className="math-frame-submit" onClick={() => onAnswer(question.answer)}>確認分數 <ChevronRight size={17} /></button>}</section>; }

function FractionCompare({ question, disabled, onAnswer }) { const [selected, setSelected] = useState(null); const answer = (value) => { if (disabled) return; setSelected(value); }; const submit = () => selected && onAnswer(selected); return <section className="fraction-compare"><div className="compare-pies">{[['left', question.left], ['right', question.right]].map(([side, value]) => { const label = `${value.filled}/${value.total}`; return <Pie key={side} total={value.total} filled={value.filled} label={label} draggable={!disabled} selected={selected === label} onDragStart={(event) => event.dataTransfer.setData('text/plain', label)} onClick={() => answer(label)} />; })}</div><div className="compare-drop" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); answer(event.dataTransfer.getData('text/plain')); }} onClick={submit} role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter') submit(); }}><span>較大的分數</span><b>{selected || '拖曳或點選一個圓餅'}</b></div></section>; }

export default function MathInteractiveActivity({ unit, onBack, onComplete }) {
  const [questions, setQuestions] = useState(() => shuffle(unit.questions)); const [index, setIndex] = useState(0); const [feedback, setFeedback] = useState(null); const [attempts, setAttempts] = useState(0); const [correct, setCorrect] = useState(0); const [showSummary, setShowSummary] = useState(false);
  const question = questions[index]; const choices = useMemo(() => shuffle(question.choices), [question]);
  const answer = (choice) => { if (feedback) return; const isCorrect = choice === question.answer; setAttempts((value) => value + 1); if (isCorrect) setCorrect((value) => value + 1); setFeedback({ correct: isCorrect, choice }); };
  const next = () => { if (index === questions.length - 1) { pauseExamTimer(); onComplete?.(unit, questions.map((item) => item.id)); setShowSummary(true); } else { setIndex((value) => value + 1); setFeedback(null); } };
  const replay = () => { setQuestions(shuffle(unit.questions)); setIndex(0); setFeedback(null); setAttempts(0); setCorrect(0); setShowSummary(false); };
  if (showSummary) return <main className="site-shell math-activity-page"><Frame unit={unit} task="結算" /><UnitResultSummary unit={unit} total={questions.length} correct={correct} attempts={attempts} onBack={onBack} onReplay={replay} title="互動數學任務完成" description="教師可根據答對題數、正確率及作答時間安排重溫。" noun="題" backLabel="返回數學目錄" /></main>;
  const isShopping = unit.interaction === 'math-shopping'; const isBuild = unit.interaction === 'math-fraction-pie'; const isCompare = unit.interaction === 'math-fraction-compare';
  return <main className="site-shell math-activity-page"><Frame unit={unit} task={`任務 ${index + 1} / ${questions.length}`} /><header className="match-topbar math-match-topbar"><button onClick={onBack} className="match-back">返回數學目錄</button><div><span>{unit.area}・{unit.title}</span><b>第 {index + 1} / {questions.length} 題</b></div><div className="match-progress"><i style={{ width: `${((index + 1) / questions.length) * 100}%` }} /></div></header><section className="math-activity-stage"><div className="math-heading"><span><Sparkles size={16} /> {isShopping ? '購物籃互動' : isBuild ? '拖曳切餅' : '分數比較操作'}</span><h1>{question.prompt}</h1><p>老師提示：先操作圖像材料，再選擇或確認答案。</p></div><section className="math-worksheet">{isShopping ? <ShoppingBasket key={question.id} question={question} disabled={Boolean(feedback)} onAnswer={answer} /> : isBuild ? <FractionBuild key={question.id} question={question} disabled={Boolean(feedback)} onAnswer={answer} /> : <FractionCompare key={question.id} question={question} disabled={Boolean(feedback)} onAnswer={answer} />}{isShopping && !feedback ? <section className="math-answer-zone"><div className="bank-title"><span>選擇找續</span><small>也可直接按購物籃的找續區確認</small></div><div className="math-option-grid">{choices.map((choice, choiceIndex) => <button key={choice} onClick={() => answer(choice)}><span>{String.fromCharCode(65 + choiceIndex)}</span><b>${choice}</b></button>)}</div></section> : null}{isCompare && !feedback ? <section className="math-answer-zone"><div className="bank-title"><span>選擇較大的分數</span><small>拖曳或點選圓餅均可</small></div><div className="math-option-grid">{choices.map((choice, choiceIndex) => <button key={choice} onClick={() => answer(choice)}><span>{String.fromCharCode(65 + choiceIndex)}</span><b>{choice}</b></button>)}</div></section> : null}</section>{feedback && <section className={`math-feedback ${feedback.correct ? 'correct' : 'incorrect'}`}><div>{feedback.correct ? <Check size={22} /> : <X size={22} />}</div><section><b>{feedback.correct ? '答對了！' : '這次還未選中正確答案。'}</b><p>{feedback.correct ? question.explanation : <>正確答案是 <strong>{question.answer}</strong>。{question.explanation}</>}</p><div className="complete-actions">{feedback.correct ? <button onClick={next}>{index === questions.length - 1 ? '查看結算' : '下一題'} <ChevronRight size={17} /></button> : <button onClick={() => setFeedback(null)}><RotateCcw size={16} /> 依提示再試</button>}<button onClick={onBack}><ArrowLeft size={16} /> 返回數學目錄</button></div></section></section>}</section></main>;
}
